@startuml
autonumber

database "Cluster" as cluster #blue
database "Cluster API CR" as capiCR #blue
database "Cluster API Infra CR" as capiInfraCR #blue
control "dns-operator-route53" as dnsOperator #blue
participant "Route 53" as route53 #orange

dnsOperator -> capiCR: watch on CAPI CR
dnsOperator -> capiInfraCR: get corresponding Infra CRs
dnsOperator -> capiCR: set the finalizer
dnsOperator -> capiInfraCR: set the finalizer
dnsOperator -> capiCR: get controlPlaneIP
dnsOperator -> route53: create ""DNS A record"" for controlPlaneIP ""api.<clusterName>.<baseDomain>""
dnsOperator -> capiInfraCR: get Bastion IP if Bastion exists(only if InfraCR is OpenStack)
dnsOperator -> route53: create ""DNS A record"" for bastion IP ""bastion1.<clusterName>.<baseDomain>""
dnsOperator -> cluster: get ""kube-system/nginx-ingress-controller"" IP if exists
dnsOperator -> route53: create ""DNS A record"" for ingress in ""kube-system"" (""ingress.<clusterName>.<baseDomain>"")
dnsOperator -> route53: create ""DNS CNAME"" ""*.<clusterName>.<baseDomain>"" point to ""ingress.<clusterName>.<baseDomain>""

@enduml